In [1]:
import numpy as np
print(np.__version__)

2.3.3


In [2]:
# working with numPy arrays
a = np.array([1, 2, 3, 4, 5, 6, 7])
print(a)
print(type(a))
a *= 2
print(a)
print(a.ndim)


# 2 dimensional array
b = np.array([[1, 2, 3, 4],
              [2, 3, 4, 5],
              [3, 4, 5, 6]])
print(b)
print(b.ndim)

# 3d array
c = np.array([[[1, 2, 3], [2, 3, 4], [3, 4, 5]], [[1, 2, 3], [
             2, 3, 4], [3, 4, 5]], [[4, 5, 6], [5, 6, 7], [6, 7, 8]]])
print(c.ndim)
print(c.shape)

# multi dimensional indexing
# 1d
print(a[0])
print(a[2])
#2d
print(b[0,1])
print(b[2,3])
print(b[1])
#3d
print(c[0,0,0]) #specific element
print(c[2,1]) # specific row
print(c[1]) # specific layer

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
[ 2  4  6  8 10 12 14]
1
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
2
3
(3, 3, 3)
2
6
2
6
[2 3 4 5]
1
[5 6 7]
[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [3]:
# slicing in NumPy array
d = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [2, 4, 6, 8],
              [1, 3, 5, 7]])
# print(d)
# print(d.ndim)
# print(d.shape)
# print all elements
print(d[:])
# row selection
print(d[::2])
print(d[::-2]) # return every 2nd row in reverse
print(d[::-1]) # return the whole in reverse
print(d[:3])


[[1 2 3 4]
 [5 6 7 8]
 [2 4 6 8]
 [1 3 5 7]]
[[1 2 3 4]
 [2 4 6 8]]
[[1 3 5 7]
 [5 6 7 8]]
[[1 3 5 7]
 [2 4 6 8]
 [5 6 7 8]
 [1 2 3 4]]
[[1 2 3 4]
 [5 6 7 8]
 [2 4 6 8]]


In [15]:
# # column selection
# print(d[::, ::-1])

# row and column selection
print(d[::-2, ::-2])

[[7 3]
 [8 6]]


In [16]:
#arithmetic operations
print(d+2)
print(d-2)
print(d*3)
print(d/2)
print(d%2)
print(d**2)
print(d//2)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [ 4  6  8 10]
 [ 3  5  7  9]]
[[-1  0  1  2]
 [ 3  4  5  6]
 [ 0  2  4  6]
 [-1  1  3  5]]
[[ 3  6  9 12]
 [15 18 21 24]
 [ 6 12 18 24]
 [ 3  9 15 21]]
[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [1.  2.  3.  4. ]
 [0.5 1.5 2.5 3.5]]
[[1 0 1 0]
 [1 0 1 0]
 [0 0 0 0]
 [1 1 1 1]]
[[ 1  4  9 16]
 [25 36 49 64]
 [ 4 16 36 64]
 [ 1  9 25 49]]
[[0 1 1 2]
 [2 3 3 4]
 [1 2 3 4]
 [0 1 2 3]]


In [ ]:
# vectorized math functions
e = np.array([1.2, 4.55, 7.8822, 7.992])
print(np.square(e))
print(np.sqrt(e))
print(np.round(e))
print(np.floor(e))
print(np.ceil(e))
print(np.pi)

[ 1.44       20.7025     62.12907684 63.872064  ]
[1.09544512 2.1330729  2.8075256  2.82701256]
[1. 5. 8. 8.]
[1. 4. 7. 7.]
[2. 5. 8. 8.]
3.141592653589793


In [24]:
#  element wise arithmetic
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([5, 6, 7, 8, 9])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1 % a2)
print(a1**a2)
print(a1//a2)

[ 6  8 10 12 14]
[-4 -4 -4 -4 -4]
[ 5 12 21 32 45]
[0.2        0.33333333 0.42857143 0.5        0.55555556]
[1 2 3 4 5]
[      1      64    2187   65536 1953125]
[0 0 0 0 0]


In [29]:
# comparison operators
s = np.array([22,442,332,23,23422,2342,34,2,2415567,4,64,4,22])
print(s>100)
print(s==100)
print(s<100)
print(s<=100)
print(s>=100)

# we can assign value to specific places too
s[s<1000] = 1234
print(s)

[False  True  True False  True  True False False  True False False False
 False]
[False False False False False False False False False False False False
 False]
[ True False False  True False False  True  True False  True  True  True
  True]
[ True False False  True False False  True  True False  True  True  True
  True]
[False  True  True False  True  True False False  True False False False
 False]
[   1234    1234    1234    1234   23422    2342    1234    1234 2415567
    1234    1234    1234    1234]


In [ ]:
# broadcasting
# allows element wise operation to be performed on the arrays by virtually expanding dimensions
b1 =  np.array([[1,2,3,4,5,6,7,8,9,10]])
b2 = np.array([[1], 
              [2], 
              [3], 
              [4]])
b3 = np.array([[1],
               [2],
               [3],
               [4],
               [5],
               [6],
               [7],
               [8],
               [9],
               [10]])
print(b1.shape)
print(b2.shape)
print(b3.shape)

print(b1+b3)

(1, 10)
(4, 1)
(10, 1)
[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [ ]:
# aggregate functions
print(np.sum(b1+b3))
print(np.min(b1+b3))
print(np.max(b1+b3))
print(np.argmax(b1+b3)) # return maximum value containing index
print(np.argmin(b1+b3)) # return the min value containing index
print(np.mean(b1+b3))
print(np.median(b1+b3))
print(np.std(b1+b3))
print(np.var(b1+b3))
print(np.sum(b1+b2, axis=0)) # column wise sum 
print(np.sum(b1+b2, axis=1)) # row wise sum 
print(np.mean(b1+b2, axis=1)) # row wise mean 

1100
2
20
99
0
11.0
11.0
4.06201920231798
16.5
[14 18 22 26 30 34 38 42 46 50]
[65 75 85 95]
[6.5 7.5 8.5 9.5]


In [65]:
# filtering
ages = np.array([[21, 17, 18, 20, 18, 17],
                [33, 51, 12, 18, 19, 10]])
teenagers = ages[ages <= 18]
adults = ages[(ages>18) & (ages<=40)] 
# numPy used C styled arrays internally so we have to use & instead of and
# this also applies to other operators such as or, etc.
evens = ages[ages%2==0]
print(teenagers)
print(adults)
print(evens)

# if we need to preserve the shape, use WHERE function
seniors = np.where(ages>=50, ages, np.nan)
print(seniors)

[17 18 18 17 12 18 10]
[21 20 33 19]
[18 20 18 12 18 10]
[[nan nan nan nan nan nan]
 [nan 51. nan nan nan nan]]


In [ ]:
# random numbers

rng = np.random.default_rng()
# to use seed, pass seed as parameter
# rng = np.random.default_rng(seed=2) 
# print(rng.integers(low=1, high=22, size=(2, 3, 4, 2)))
print(rng.integers(low=1,high=3, size=(4))) # random integer of given dimensions and size


[2 1 1 2]
1
1.720324493442158


In [117]:

# to set the seed for uniform
np.random.seed(seed=1)
print(int(np.random.uniform(low=1, high=2))) # random integer number
print((np.random.uniform(low=1, high=2))) # random floating number

1
1.720324493442158


In [125]:
# random selection from array
rng = np.random.default_rng()
# rng = np.random.default_rng(seed=1) to print a fixed value each time
fruits = ["apple", "banana", "coconut", "dragonfruit", "eggplant", "fig", "guava"]
fruit = rng.choice(fruits)
fruit = rng.choice(fruits, size=(3,2))
print(fruit)

[['eggplant' 'dragonfruit']
 ['guava' 'dragonfruit']
 ['eggplant' 'fig']]
