In [1]:
import numpy as np
print(np.__version__)

2.3.3


In [2]:
# working with numPy arrays
a = np.array([1, 2, 3, 4, 5, 6, 7])
print(a)
print(type(a))
a *= 2
print(a)
print(a.ndim)


# 2 dimensional array
b = np.array([[1, 2, 3, 4],
              [2, 3, 4, 5],
              [3, 4, 5, 6]])
print(b)
print(b.ndim)

# 3d array
c = np.array([[[1, 2, 3], [2, 3, 4], [3, 4, 5]], [[1, 2, 3], [
             2, 3, 4], [3, 4, 5]], [[4, 5, 6], [5, 6, 7], [6, 7, 8]]])
print(c.ndim)
print(c.shape)

# multi dimensional indexing
# 1d
print(a[0])
print(a[2])
#2d
print(b[0,1])
print(b[2,3])
print(b[1])
#3d
print(c[0,0,0]) #specific element
print(c[2,1]) # specific row
print(c[1]) # specific layer

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
[ 2  4  6  8 10 12 14]
1
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
2
3
(3, 3, 3)
2
6
2
6
[2 3 4 5]
1
[5 6 7]
[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [3]:
# slicing in NumPy array
d = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [2, 4, 6, 8],
              [1, 3, 5, 7]])
# print(d)
# print(d.ndim)
# print(d.shape)
# print all elements
print(d[:])
# row selection
print(d[::2])
print(d[::-2]) # return every 2nd row in reverse
print(d[::-1]) # return the whole in reverse
print(d[:3])


[[1 2 3 4]
 [5 6 7 8]
 [2 4 6 8]
 [1 3 5 7]]
[[1 2 3 4]
 [2 4 6 8]]
[[1 3 5 7]
 [5 6 7 8]]
[[1 3 5 7]
 [2 4 6 8]
 [5 6 7 8]
 [1 2 3 4]]
[[1 2 3 4]
 [5 6 7 8]
 [2 4 6 8]]


In [15]:
# # column selection
# print(d[::, ::-1])

# row and column selection
print(d[::-2, ::-2])

[[7 3]
 [8 6]]


In [16]:
#arithmetic operations
print(d+2)
print(d-2)
print(d*3)
print(d/2)
print(d%2)
print(d**2)
print(d//2)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [ 4  6  8 10]
 [ 3  5  7  9]]
[[-1  0  1  2]
 [ 3  4  5  6]
 [ 0  2  4  6]
 [-1  1  3  5]]
[[ 3  6  9 12]
 [15 18 21 24]
 [ 6 12 18 24]
 [ 3  9 15 21]]
[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [1.  2.  3.  4. ]
 [0.5 1.5 2.5 3.5]]
[[1 0 1 0]
 [1 0 1 0]
 [0 0 0 0]
 [1 1 1 1]]
[[ 1  4  9 16]
 [25 36 49 64]
 [ 4 16 36 64]
 [ 1  9 25 49]]
[[0 1 1 2]
 [2 3 3 4]
 [1 2 3 4]
 [0 1 2 3]]


In [ ]:
# vectorized math functions
e = np.array([1.2, 4.55, 7.8822, 7.992])
print(np.square(e))
print(np.sqrt(e))
print(np.round(e))
print(np.floor(e))
print(np.ceil(e))
print(np.pi)

[ 1.44       20.7025     62.12907684 63.872064  ]
[1.09544512 2.1330729  2.8075256  2.82701256]
[1. 5. 8. 8.]
[1. 4. 7. 7.]
[2. 5. 8. 8.]
3.141592653589793


In [24]:
#  element wise arithmetic
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([5, 6, 7, 8, 9])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1 % a2)
print(a1**a2)
print(a1//a2)

[ 6  8 10 12 14]
[-4 -4 -4 -4 -4]
[ 5 12 21 32 45]
[0.2        0.33333333 0.42857143 0.5        0.55555556]
[1 2 3 4 5]
[      1      64    2187   65536 1953125]
[0 0 0 0 0]


In [29]:
# comparison operators
s = np.array([22,442,332,23,23422,2342,34,2,2415567,4,64,4,22])
print(s>100)
print(s==100)
print(s<100)
print(s<=100)
print(s>=100)

# we can assign value to specific places too
s[s<1000] = 1234
print(s)

[False  True  True False  True  True False False  True False False False
 False]
[False False False False False False False False False False False False
 False]
[ True False False  True False False  True  True False  True  True  True
  True]
[ True False False  True False False  True  True False  True  True  True
  True]
[False  True  True False  True  True False False  True False False False
 False]
[   1234    1234    1234    1234   23422    2342    1234    1234 2415567
    1234    1234    1234    1234]
